Repository umc-commit/commit_backend, pull requests merged in 2025-07, with the labels that each got.

#2 [FEAT] socket.io setting
  package-lock.json
  package.json
  prisma/migrations/20250706154913_init/migration.sql
  prisma/migrations/migration_lock.toml
  public/client-test.html
  src/index.js
  src/socket.js
Labels: enhancement

#4 [FEAT] create chatroom
  package-lock.json
  package.json
  prisma/migrations/20250707174939_modify_commission_artist_relation/migration.sql
  prisma/migrations/20250707183838_modify_chatroom_hidden_value/migration.sql
  prisma/schema.prisma
  prisma/seed.js
  src/bigintJson.js
  src/chat/chat.routes.js
  src/chat/controller/chatroom.controller.js
  src/chat/dto/chatroom.dto.js
  src/chat/repository/chat.repository.js
  src/chat/service/chat.service.js
  src/common/errors/BaseError.js
  src/common/errors/chat.errors.js
  src/common/errors/request.errors.js
  src/common/errors/user.errors.js
  src/common/swagger/chat.json
  src/common/swagger/index.js
  src/common/swagger/user.js
  src/index.js
  src/request/repository/request.repository.js
  src/routes.js
  src/user/repository/user.repository.js
Labels: enhancement

#7 [Feat] 채팅방 조회, 삭제 기능 구현
  src/chat/chat.routes.js
  src/chat/controller/chatroom.controller.js
  src/chat/dto/chatroom.dto.js
  src/chat/repository/chat.repository.js
  src/chat/service/chat.service.js
  src/common/errors/chat.errors.js
  src/common/swagger/chat.json
  src/routes.js
Labels: enhancement

#11 [FEAT] 리뷰 이미지 업로드 및 작성 API
  .gitignore
  package-lock.json
  package.json
  prisma/schema.prisma
  src/common/errors/review.errors.js
  src/review/controller/review.controller.js
  src/review/repository/index.js
  src/review/repository/review.repository.js
  src/review/review.routes.js
  src/review/service/review.service.js
  src/routes.js
Labels: enhancement

#19 [FEAT] 네이버 소셜 로그인 구현
  package-lock.json
  package.json
  src/auth.config.js
  src/common/swagger/user.json
  src/index.js
  src/user/user.routes.js
Labels: enhancement

#26 [FEAT] 리뷰 수정 및 삭제 API
  package-lock.json
  prisma/migrations/20250714163955_add_updated_at_to_review/migration.sql
  prisma/schema.prisma
  src/common/swagger/review.json
  src/review/controller/review.controller.js
  src/review/dto/review.dto.js
  src/review/repository/review.repository.js
  src/review/review.routes.js
  src/review/service/review.service.js
Labels: enhancement

#38 [FEAT] 사용자별 리뷰 목록 조회 API
  src/common/swagger/review.json
  src/review/controller/review.controller.js
  src/review/dto/review.dto.js
  src/review/repository/review.repository.js
  src/review/service/review.service.js
  src/user/user.routes.js
Labels: enhancement

#42 [Feat] 나의 프로필 수정 API
  src/common/swagger/user.json
  src/user/controller/user.controller.js
  src/user/dto/user.dto.js
  src/user/repository/user.repository.js
  src/user/service/user.service.js
  src/user/user.routes.js
Labels: enhancement

#44 [FEAT] 결제 및 결제완료 처리
  package-lock.json
  package.json
  prisma/migrations/20250721005213_add_amount_and_payment_fields/migration.sql
  prisma/migrations/20250721015050_add_unique_to_point_user_id/migration.sql
  prisma/migrations/20250721025720_remove_request_from_payment/migration.sql
  prisma/schema.prisma
  prisma/seed.js
  src/common/errors/payment.errors.js
  src/common/swagger/payment.json
  src/index.js
  src/payment/controller/payment.controller.js
  src/payment/dto/payment.dto.js
  src/payment/payment.routes.js
  src/payment/repository/payment.repository.js
  src/payment/service/payment.service.js
  src/point/repository/point.repository.js
  src/routes.js
  views/client-paytest.ejs
Labels: enhancement

#47 [FEAT] 알림 관리 API
  prisma/migrations/20250720014557_add_notification_fields/migration.sql
  prisma/schema.prisma
  src/common/errors/notification.errors.js
  src/common/swagger/notification.json
  src/notification/controller/notification.controller.js
  src/notification/dto/notification.dto.js
  src/notification/notification.routes.js
  src/notification/repository/notification.repository.js
  src/notification/service/notification.service.js
  src/review/controller/review.controller.js
  src/routes.js
Labels: enhancement

#56 [FEAT] 사용자 닉네임 중복 확인하기
  src/common/swagger/user.json
  src/user/controller/user.controller.js
  src/user/repository/user.repository.js
  src/user/service/user.service.js
  src/user/user.routes.js
Labels: enhancement

#60 [FEAT] 작가 회원가입 + 기존의 회원가입 코드에 role 추가
  src/artist/repository/artist.repository.js
  src/common/errors/user.errors.js
  src/common/swagger/user.json
  src/user/controller/user.controller.js
  src/user/dto/user.dto.js
  src/user/repository/user.repository.js
  src/user/service/user.service.js
Labels: enhancement

#62 [FEAT] 채팅 내용 검색
  public/client-test.html
  src/chat/chat.routes.js
  src/chat/controller/chat.controller.js
  src/chat/dto/chat.dto.js
  src/chat/repository/chat.repository.js
  src/chat/service/chat.service.js
  src/common/swagger/chat.json
  src/user/repository/user.repository.js
Labels: enhancement

#68 [FEAT] 사용자가 원하는 작가 팔로우
  src/common/errors/user.errors.js
  src/common/swagger/user.json
  src/user/controller/user.controller.js
  src/user/repository/user.repository.js
  src/user/service/user.service.js
  src/user/user.routes.js
Labels: enhancement

#70 [FEAT] 결제 내역 조회
  prisma/migrations/20250723130401_add_point_amount_to_payment/migration.sql
  prisma/migrations/20250723155205_add_total_price_to_request/migration.sql
  prisma/schema.prisma
  prisma/seed.js
  src/artist/repository/artist.repository.js
  src/common/errors/payment.errors.js
  src/common/swagger/payment.json
  src/payment/controller/payment.controller.js
  src/payment/payment.routes.js
  src/payment/repository/payment.repository.js
  src/payment/service/payment.service.js
Labels: enhancement

#80 [FEAT] 사용자 포인트 사용
  package-lock.json
  src/common/errors/point.errors.js
  src/common/swagger/point.json
  src/payment/dto/payment.dto.js
  src/point/controller/point.controller.js
  src/point/dto/point.dto.js
  src/point/point.routes.js
  src/point/service/point.service.js
  src/user/user.routes.js
Labels: bug, enhancement

#84 [FEAT] FCM Push 알림
  .gitignore
  package-lock.json
  package.json
  prisma/migrations/20250723125127_add_push_token/migration.sql
  prisma/schema.prisma
  src/common/errors/notification.errors.js
  src/common/errors/review.errors.js
  src/common/swagger/notification.json
  src/firebase.config.js
  src/notification/fcm/controller/push.controller.js
  src/notification/fcm/dto/push.dto.js
  src/notification/fcm/repository/push.repository.js
  src/notification/fcm/service/push.service.js
  src/notification/notification.routes.js
  src/notification/service/notification.service.js
  src/request/request.routes.js
  src/review/repository/review.repository.js
  src/review/review.routes.js
  src/review/service/review.service.js
  src/routes.js
Labels: enhancement

#94 [FEAT] 제출된 신청서 조회
  src/commission/service/commission.service.js
  src/common/swagger/request.json
  src/request/controller/request.controller.js
  src/request/dto/request.dto.js
  src/request/repository/request.repository.js
  src/request/request.routes.js
  src/request/service/request.service.js
Labels: enhancement

#100 [FEAT] 완료된 신청내역 조회
  src/common/swagger/request.json
  src/request/controller/request.controller.js
  src/request/dto/request.dto.js
  src/request/repository/request.repository.js
  src/request/request.routes.js
  src/request/service/request.service.js
Labels: enhancement

#109 [FEAT] 작업물 조회
  src/common/errors/request.errors.js
  src/common/swagger/request.json
  src/request/controller/request.controller.js
  src/request/dto/request.dto.js
  src/request/repository/request.repository.js
  src/request/request.routes.js
  src/request/service/request.service.js
Labels: enhancement

#110 [FIX] BigInt(undefined) 서버 오류 해결
  src/common/errors/notification.errors.js
  src/common/errors/review.errors.js
  src/notification/controller/notification.controller.js
  src/notification/fcm/controller/push.controller.js
  src/review/controller/review.controller.js
Labels: bug
